# Generated by Django 6.1.1 on 2026-09-25 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("fridge", "Fridge"),
                            ("freezer", "Freezer"),
                            ("walk_in", "Walk-in"),
                            ("prep_table", "Prep table"),
                            ("other", "Other"),
                        ],
                        default="fridge",
                        max_length=32,
                    ),
                ),
                ("min_temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_temp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TemperatureReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("business_date", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("corrective_action", models.TextField(blank=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="temperatures.equipment",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="temperature_readings",
                        to="core.location",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="temperature_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-business_date", "-recorded_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(
                fields=("location", "name"), name="unique_equipment_per_location"
            ),
        ),
        migrations.AddIndex(
            model_name="temperaturereading",
            index=models.Index(
                fields=["equipment", "business_date"],
                name="temperature_equipme_843a13_idx",
            ),
        ),
    ]
