# Generated by Django 6.1.1 on 2026-09-25 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("unit", models.CharField(max_length=50)),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waste_items",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="WasteEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spoilage", "Spoilage"),
                            ("prep_error", "Prep error"),
                            ("customer_return", "Customer return"),
                            ("expired", "Expired"),
                            ("over_production", "Over production"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "cost_at_entry",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("business_date", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waste_entries",
                        to="core.location",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waste_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="waste.wasteitem",
                    ),
                ),
            ],
            options={
                "ordering": ("-business_date", "-recorded_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="wasteitem",
            constraint=models.UniqueConstraint(
                fields=("location", "name"), name="unique_waste_item_per_location"
            ),
        ),
        migrations.AddIndex(
            model_name="wasteentry",
            index=models.Index(
                fields=["location", "business_date"],
                name="waste_waste_locatio_ec2f07_idx",
            ),
        ),
    ]
